import random

questions = [
  "1. What date is Christmas celebrated on?",
  "2. What Christian denomination celebrates Christmas on January 7th?",
  "3. In which country did the tradition of placing Christmas trees in homes originate?",
  "4. What is the name of the famous ballet performed at Christmas time?",
  "5. What is another name for Santa Claus?",
  "6. Which plant is often associated with Christmas?",
  "7. What is the first line of the famous Christmas carol 'Jingle Bells'?",
  "8. Which country celebrates St. Lucia Day on December 13th?",
  "9. Which famous scientist is credited with creating the first electric Christmas lights?",
  "10. What are the colors traditionally associated with Christmas?",
  "11. What is the name of the famous reindeer with a red nose?",
  "12. In the movie 'Home Alone', where are the McCallisters going for Christmas vacation?",
  "13. What is the name of the Grinch's dog in the story 'How the Grinch Stole Christmas'?",
  "14. What is the traditional meat served for Christmas dinner in the United States?",
  "15. In Charles Dickens' 'A Christmas Carol', which character is visited by three ghosts?",
  "16. Which country is credited with starting the tradition of exchanging gifts on Christmas?",
  "17. What is the name of the angel who visits Mary to announce the birth of Jesus?",
  "18. According to legend, if you find the hidden almond in the Christmas pudding, what will happen?",
  "19. What holiday is celebrated on December 26th?",
  "20. What is the name of the elf who wants to be a dentist in the movie 'Rudolph the Red-Nosed Reindeer'?",
  "21. In 'The Twelve Days of Christmas' song, what is given on the fifth day?",
  "22. What is the name of the snowman who comes to life in the movie 'Frosty the Snowman'?",
  "23. What is the name of the city where Jesus was born?",
  "24. What is the traditional Christmas dessert in England?",
  "25. Why do people hang stockings by the fireplace on Christmas Eve?",
  "26. What is the name of the town that is the setting for the movie 'It's a Wonderful Life'?",
  "27. What is the name of the main character in the movie 'Elf'?",
  "28. What is the traditional Christmas flower?",
  "29. Who wrote the poem 'Twas the Night Before Christmas'?",
  "30. How many reindeer pull Santa's sleigh?",
  "31. What is the name of the little boy in the movie 'A Christmas Story' who wants a BB gun for Christmas?",
  "32. What is the name of the family in the TV show 'The Brady Bunch' who received a surprise visit from their grandfather on Christmas?",
  "33. What is the name of the town in which the animated TV special 'A Charlie Brown Christmas' takes place?",
  "34. What is the name of the reindeer who leads Santa's sleigh?",
  "35. What is the traditional Christmas greeting in England?",
  "36. Which US state was the first to declare Christmas as a legal holiday?",
  "37. What is the name of the author of 'The Nutcracker' ballet?",
  "38. What are candy canes traditionally shaped like?",
  "39. What is the name of the main character in the movie 'How the Grinch Stole Christmas'?",
  "40. How many points does a snowflake typically have?",
  "41. What is the name of the main character in the book 'A Christmas Carol'?",
  "42. What is the name of the toy that The Simpsons adopt as a pet for Christmas in the episode 'Simpsons Roasting on an Open Fire'?",
  "43. What is the name of the little girl in the movie 'Miracle on 34th Street' who believes in Santa Claus?",
  "44. What is the name of the reindeer with silver bells on his harness in the song 'Jingle Bells'?",
  "45. In 'The Polar Express' movie, what is the first gift of Christmas?",
  "46. What is the name of the brother in the movie 'A Christmas Story' who always wears a hat?",
  "47. In the TV show 'Friends', what did Ross dress up as in the Christmas episode?",
  "48. What is the name of the personification of Snow in the movie 'Frozen'?",
  "49. Which department store is known for its elaborate Christmas window displays in New York City?",
  "50. How many ghosts visit Ebenezer Scrooge in 'A Christmas Carol'?",
  "51. In 'How the Grinch Stole Christmas', what does the Grinch use to pull his sled?",
  "52. What is the name of the Scrooge's dead business partner in 'A Christmas Carol'?",
  "53. What type of cake is traditionally eaten in Italy on Christmas Day?",
  "54. Which note is the highest in the Christmas carol 'O Holy Night'?",
  "55. What is the name of the little girl who befriends the Grinch in 'How the Grinch Stole Christmas'?",
  "56. In the song 'White Christmas', who is dreaming of a white Christmas?",
  "57. What is the name of the brother in the movie 'Home Alone' who is left behind?",
  "58. In the movie 'How the Grinch Stole Christmas', what is the Grinch's heart said to be 'two sizes too'?",
  "59. What is the name of the fairy who grants Pinocchio's wish to become a real boy on Christmas Eve?",
  "60. What does the French phrase 'Joyeux Noël' mean in English?",
  "61. In the TV show 'The Office', what does Dwight dress up as in the Christmas episode?",
  "62. How many gifts in total are given in 'The Twelve Days of Christmas' song?",
  "63. What is the name of the little boy in the movie 'Elf' who helps save Christmas?",
  "64. In the TV show 'The Big Bang Theory', what does Sheldon dress up as in the Christmas episode?",
  "65. What is the name of the main character in the book 'The Night Before Christmas'?",
  "66. In the movie 'A Christmas Carol', what is the name of Scrooge's nephew?",
  "67. What is the traditional Christmas beverage served in England?",
  "68. In the movie 'Elf', what is the first rule of The Code of Elves?",
  "69. What is the name of the dog in the movie 'National Lampoon's Christmas Vacation'?",
  "70. In 'The Nightmare Before Christmas' movie, what is Jack Skellington known as?",
  "71. What is the name of the little girl in the movie 'Home Alone' who becomes friends with Kevin McCallister?",
  "72. In the song 'Frosty the Snowman', what are the children's names who bring Frosty to life?",
  "73. What is the name of the reindeer who is constantly worried about his order on Santa's list in the movie 'Arthur Christmas'?",
  "74. In the TV show 'Seinfeld', what is the name of the holiday celebrated by George Costanza's father?",
  "75. What type of bird is often served for Christmas dinner in England?",
  "76. In the movie 'The Santa Clause', what is the name of Santa's head elf?",
  "77. What is the name of the little boy in the movie 'The Polar Express' who questions the existence of Santa Claus?",
  "78. In the song 'Rudolph the Red-Nosed Reindeer', what is the name of Rudolph's girlfriend?",
  "79. What is the name of the dog in the movie 'How the Grinch Stole Christmas'?",
  "80. In the TV show 'Friends', what does Monica make Chandler wear in the Christmas episode?",
  "81. Who is the author of the book 'The Night Before Christmas'?",
  "82. In the movie 'The Polar Express', what does the conductor punch to validate the children's tickets?",
  "83. What is the name of the main character in the movie 'A Christmas Carol' played by Jim Carrey?",
  "84. In 'The Nutcracker' ballet, what is the name of the prince?",
  "85. What is the name of the little girl in the movie 'A Christmas Carol' who is sick and later dies?",
  "86. In the movie 'Elf', what does Buddy find out he is not?",
  "87. What is the name of the little girl in the movie 'Miracle on 34th Street' who is friends with Kris Kringle?",
  "88. What is the name of the main character in the movie 'The Santa Clause' played by Tim Allen?",
  "89. In the TV show 'How I Met Your Mother', what is the name of Barney's Christmas-themed video?",
  "90. What is the name of the snowman in the movie 'The Snowman'?",
  "91. In the movie 'A Christmas Story', what is the name of the bully who always torments Ralphie?",
  "92. What is the name of the main character in the movie 'The Polar Express' played by Tom Hanks?",
  "93. In the TV show 'Friends', what present does Ross buy for his son Ben in the Christmas episode?",
  "94. What is the name of the main character in the movie 'The Grinch' played by Jim Carrey?",
  "95. In the movie 'Home Alone', what is Kevin's last name?",
  "96. What does the Italian phrase 'Buon Natale' mean in English?",
  "97. In the movie 'The Santa Clause', what is the name of Santa's ex-wife?",
  "98. What is the name of the angel in the movie 'It's a Wonderful Life' who helps George Bailey?",
  "99. In 'The Nutcracker' ballet, what is the name of the female character who leads Clara to the Land of Sweets?",
  "100. What is the name of the main character in the movie 'A Christmas Story' who wants a Red Ryder BB gun for Christmas?"
]

answers = [
  "December 25th",
  "Eastern Orthodox",
  "Germany",
  "The Nutcracker",
  "St. Nicholas",
  "Poinsettia",
  "Dashing through the snow",
  "Sweden",
  "Thomas Edison",
  "Red and green",
  "Rudolph",
  "Paris, France",
  "Max",
  "Roast turkey",
  "Ebenezer Scrooge",
  "Ancient Romans",
  "Gabriel",
  "Good luck for the next year",
  "Boxing Day",
  "Hermey",
  "Five golden rings",
  "Frosty",
  "Bethlehem",
  "Christmas pudding",
  "For Santa to fill them with gifts",
  "Bedford Falls",
  "Buddy",
  "Poinsettia",
  "Clement Clarke Moore",
  "Eight",
  "Ralphie",
  "Brady",
  "Charlie Brown",
  "Rudolph",
  "Merry Christmas",
  "Alabama",
  "Pyotr Ilyich Tchaikovsky",
  "Canes",
  "The Grinch",
  "Six",
  "Ebenezer Scrooge",
  "Santa's Little Helper",
  "Susan Walker",
  "One-Horse Open Sleigh",
  "A bell from Santa’s sleigh",
  "Randy",
  "Holiday Armadillo",
  "Elsa",
  "Macy's",
  "Four",
  "His dog",
  "Jacob Marley",
  "Panettone",
  "High",
  "Cindy Lou Who",
  "Irving Berlin",
  "Buzz",
  "Small",
  "The Blue Fairy",
  "Merry Christmas",
  "Dwight dresses up as Santa",
  "364",
  "Michael",
  "Doppler radar",
  "Santa Claus",
  "Fred",
  "Wassail",
  "Treat every day like Christmas",
  "Snots",
  "The Pumpkin King",
  "Linnie",
  "Karen and Hocus Pocus",
  "Steve",
  "Festivus",
  "Turkey",
  "Bernard",
  "Billy",
  "Clarice",
  "Max",
  "A Santa hat",
  "Clement Clarke Moore",
  "The ticket",
  "Ebenezer Scrooge",
  "The Prince/Prince Charming",
  "Tiny Tim",
  "An elf",
  "Susan Walker",
  "Scott Calvin",
  "Robin Sparkles' Let's Go to the Mall",
  "Raymond Briggs",
  "Scut Farkus",
  "The Conductor",
  "A hockey jersey",
  "The Grinch",
  "McCallister",
  "Merry Christmas",
  "Laura Miller",
  "Clarence Odbody",
  "Sugar Plum Fairy",
  "Ralphie Parker"
]

def start():
    print("Welcome to the Christmas Quiz!")
    name = input("Please enter your name to begin: ")
    number = int(input("How many questions would you like to answer? "))
    print("Good luck", name + "!")
    quiz(number)

def quiz(number):
    score = 0
    for i in range(number):
        question = random.choice(questions)
        print(question)
        answer = input("Answer: ")
        if answer in answers:
            print("Correct!")
            score += 1
        else:
            print("Incorrect!")
    print("You scored", score, "out of", number)
    again = input("Would you like to play again? (y/n) ")
    if again == "y":
        start()
    else:
        print("Thank you for playing!")

start()